export const STATUS = {
  LEADER: "leader",
  DEVELOPING: "developing",
  RESTRICTIVE: "restrictive",
  NO_DATA: "no_data",
};

export const STATUS_COLORS = {
  [STATUS.LEADER]: "#22c55e",
  [STATUS.DEVELOPING]: "#D4A017",
  [STATUS.RESTRICTIVE]: "#ef4444",
  [STATUS.NO_DATA]: "#94a3b8",
};

export const STATUS_LABELS = {
  en: {
    [STATUS.LEADER]: "Policy Leader",
    [STATUS.DEVELOPING]: "Developing",
    [STATUS.RESTRICTIVE]: "Restrictive",
    [STATUS.NO_DATA]: "No Data Yet",
  },
  fr: {
    [STATUS.LEADER]: "Leader Politique",
    [STATUS.DEVELOPING]: "En Développement",
    [STATUS.RESTRICTIVE]: "Restrictif",
    [STATUS.NO_DATA]: "Pas de Données",
  },
};

export const COUNTRY_DATA = {
  Nigeria: {
    flag: "🇳🇬",
    status: STATUS.LEADER,
    policy: 74,
    innovation: 89,
    adoption: 91,
    summary: "Africa's most active Web3 market with growing VASP regulation and high grassroots crypto adoption.",
    focus: "VASP licensing, stablecoin regulation, crypto taxation",
  },
  Rwanda: {
    flag: "🇷🇼",
    status: STATUS.LEADER,
    policy: 88,
    innovation: 72,
    adoption: 68,
    summary: "Most progressive regulatory sandbox in Africa with clear crypto licensing framework.",
    focus: "Regulatory sandboxes, VASP frameworks, fintech innovation",
  },
  "South Africa": {
    flag: "🇿🇦",
    status: STATUS.LEADER,
    policy: 81,
    innovation: 78,
    adoption: 75,
    summary: "First African nation to fully regulate crypto assets under FSCA with strong institutional adoption.",
    focus: "FSCA crypto regulation, institutional adoption, investor protection",
  },
  Kenya: {
    flag: "🇰🇪",
    status: STATUS.DEVELOPING,
    policy: 70,
    innovation: 74,
    adoption: 72,
    summary: "Active crypto community with evolving regulatory framework and strong mobile money integration.",
    focus: "Mobile money integration, VASP licensing, blockchain infrastructure",
  },
  Ghana: {
    flag: "🇬🇭",
    status: STATUS.DEVELOPING,
    policy: 65,
    innovation: 61,
    adoption: 66,
    summary: "Bank of Ghana piloting e-Cedi CBDC with cautious but progressive stance on crypto.",
    focus: "CBDC development, crypto regulation, fintech policy",
  },
  Egypt: {
    flag: "🇪🇬",
    status: STATUS.RESTRICTIVE,
    policy: 44,
    innovation: 55,
    adoption: 50,
    summary: "Crypto trading restricted under central bank guidelines though blockchain pilots ongoing.",
    focus: "Blockchain pilots, regulatory reform, digital payments",
  },
  Ethiopia: {
    flag: "🇪🇹",
    status: STATUS.DEVELOPING,
    policy: 58,
    innovation: 60,
    adoption: 54,
    summary: "Government exploring blockchain for land registry and agriculture supply chain.",
    focus: "Land registry, agriculture supply chain, CBDC exploration",
  },
  Senegal: {
    flag: "🇸🇳",
    status: STATUS.DEVELOPING,
    policy: 62,
    innovation: 58,
    adoption: 55,
    summary: "BCEAO working on regional CBDC across West Africa with growing startup ecosystem.",
    focus: "Regional CBDC, West Africa fintech, blockchain startups",
  },
  Tanzania: {
    flag: "🇹🇿",
    status: STATUS.DEVELOPING,
    policy: 55,
    innovation: 52,
    adoption: 50,
    summary: "Cautious regulatory approach with recent signals of opening toward crypto licensing.",
    focus: "Crypto licensing, mobile money, digital asset policy",
  },
  Morocco: {
    flag: "🇲🇦",
    status: STATUS.RESTRICTIVE,
    policy: 46,
    innovation: 57,
    adoption: 48,
    summary: "Crypto banned for payments but government studying regulatory framework for future adoption.",
    focus: "Regulatory reform, blockchain R&D, CBDC feasibility",
  },
  Cameroon: {
    flag: "🇨🇲",
    status: STATUS.DEVELOPING,
    policy: 60,
    innovation: 56,
    adoption: 58,
    summary: "Growing Web3 community with increasing government awareness of blockchain potential.",
    focus: "Web3 education, fintech ecosystem, policy development",
  },
  "Côte d'Ivoire": {
    flag: "🇨🇮",
    status: STATUS.DEVELOPING,
    policy: 58,
    innovation: 54,
    adoption: 52,
    summary: "Part of BCEAO regional framework with active fintech and blockchain startup scene.",
    focus: "Regional BCEAO framework, fintech startups, digital commerce",
  },
  Zimbabwe: {
    flag: "🇿🇼",
    status: STATUS.DEVELOPING,
    policy: 56,
    innovation: 50,
    adoption: 60,
    summary: "RBZ launched gold-backed digital token with growing interest in crypto as inflation hedge.",
    focus: "Gold-backed digital token, inflation hedge crypto, CBDC",
  },
  Zambia: {
    flag: "🇿🇲",
    status: STATUS.DEVELOPING,
    policy: 54,
    innovation: 48,
    adoption: 50,
    summary: "SEC Zambia exploring crypto regulation with cautious but open approach.",
    focus: "SEC crypto regulation, investor protection, digital assets",
  },
};